// Generated by Wrangler on Wed Oct 23 2024 18:48:18 GMT-0500 (Central Daylight Time)
// by running `wrangler types`

interface Env {
	"solarlabyrinth.dev": KVNamespace;
	ITCH_IO_API_KEY: string;
	IS_LOCAL: string;
}
