// Generated by Wrangler on Wed Oct 23 2024 21:33:08 GMT-0500 (Central Daylight Time)
// by running `wrangler types`

export {};
interface Env {
  "solarlabyrinth.dev": KVNamespace;
  ITCH_IO_API_KEY: string;
  IS_LOCAL?: string;
  USE_CACHE?: string;
}
